// Import React
// =========================================================
   import React from 'react';
// Import Material Ui Components
// =========================================================
  import { makeStyles } from '@material-ui/core/styles';
  import Paper from '@material-ui/core/Paper';
  import Table from '@material-ui/core/Table';
  import TableBody from '@material-ui/core/TableBody';
  import TableCell from '@material-ui/core/TableCell';
  import TableContainer from '@material-ui/core/TableContainer';
  import TableHead from '@material-ui/core/TableHead';
  import TablePagination from '@material-ui/core/TablePagination';
  import TableRow from '@material-ui/core/TableRow';


// Test Data
// =========================================================

//   OUTPUT - Modal Data
const columnsModal = [
    { 
        id: 'dc',
        label: 'DC', 
        // minWidth: 40 
        align: 'center',
    },
    {
      id: 'packId',
      label: 'Pack ID',
    //   minWidth: 40,
      align: 'center',
      // format: value => value.toLocaleString(),
    },
    {
      id: 'remaining',
      label: 'Remaining',
    //   minWidth: 20,
      align: 'center',
      format: value => value.toFixed(2),
    },
    {
        id: 'remove',
        label: '',
        // minWidth: 20,
        align: 'center',
        format: value => value.toFixed(2),
      },
    {
      id: 'allocated',
      label: 'Allocated',
    //   minWidth: 40,
      align: 'center',
      format: value => value.toFixed(2),
    },
    {
        id: 'add',
        label: '',
        // minWidth: 20,
        align: 'center',
        format: value => value.toFixed(2),
      },
  ];
  function createModalData(dc, packId, remaining, remove, allocated, add) {
    return {dc, packId, remaining, remove, allocated, add};
  }
  
  const rowsModal = [
    createModalData( "DC1", "Bulk_XS", "6", renderMinus(), "0", renderPlus()),
    createModalData( "DC1", "Bulk_S", "51", renderMinus(), "1", renderPlus()),
    createModalData( "DC1", "Bulk_M", "46", renderMinus(), "4", renderPlus()),
    createModalData( "DC1", "Bulk_L", "215", renderMinus(), "5", renderPlus()),
    createModalData( "DC1", "Bulk_XL", "71", renderMinus(), "3", renderPlus()),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6003", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6003", "Bulk_S", 51, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6003", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6003", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6003", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6006", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6006", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6006", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6006", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6006", "Bulk_XL", 71, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6007", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6007", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6007", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6007", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6007", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6011", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6011", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6011", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6011", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6011", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6013", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6013", "Bulk_S", 51, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6013", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6013", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6013", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6016", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6016", "Bulk_S", 51, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6016", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6016", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6016", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6020", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6020", "Bulk_S", 51, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6020", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6020", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6020", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6028", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6028", "Bulk_S", 51, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6028", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6028", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6028", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6029", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6029", "Bulk_S", 51, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6029", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6029", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6029", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6030", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6030", "Bulk_S", 51, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6030", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6030", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6030", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6031", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6031", "Bulk_S", 51, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6031", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6031", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6031", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6035", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6035", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6035", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6035", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6035", "Bulk_XL", 71, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6038", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6038", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6038", "Bulk_M", 46, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6038", "Bulk_L", 215, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6038", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6042", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6042", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6042", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6042", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6042", "Bulk_XL", 71, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6046", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6046", "Bulk_S", 51, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6046", "Bulk_M", 46, 4),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6046", "Bulk_L", 215, 4),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6046", "Bulk_XL", 71, 3),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6052", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6052", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6052", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6052", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6052", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6054", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6054", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6054", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6054", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6054", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6056", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6056", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6056", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6056", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6056", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6058", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6058", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6058", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6058", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6058", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6059", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6059", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6059", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6059", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6059", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6061", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6061", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6061", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6061", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6061", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6066", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6066", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6066", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6066", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6066", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6082", "Bulk_XS", 6, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6082", "Bulk_S", 51, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6082", "Bulk_M", 46, 3),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6082", "Bulk_L", 215, 3),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6082", "Bulk_XL", 71, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6089", "Bulk_XS", 6, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6089", "Bulk_S", 51, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6089", "Bulk_M", 46, 3),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6089", "Bulk_L", 215, 3),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6089", "Bulk_XL", 71, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6101", "Bulk_XS", 6, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6101", "Bulk_S", 51, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6101", "Bulk_M", 46, 3),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6101", "Bulk_L", 215, 3),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6101", "Bulk_XL", 71, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6131", "Bulk_XS", 6, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6131", "Bulk_S", 51, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6131", "Bulk_M", 46, 3),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6131", "Bulk_L", 215, 3),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6131", "Bulk_XL", 71, 2),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6199", "Bulk_XS", 6, 16),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6199", "Bulk_S", 51, 25),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6199", "Bulk_M", 46, 138),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6199", "Bulk_L", 215, 146),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6199", "Bulk_XL", 71, 119),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6221", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6221", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6221", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6221", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6221", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6222", "Bulk_XS", 6, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6222", "Bulk_S", 51, 0),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6222", "Bulk_M", 46, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6222", "Bulk_L", 215, 1),
    // createModalData( "DC1", "Dicte Mini Skirt Checked-Pale Blue/Black", "6222", "Bulk_XL", 71, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6001", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6001", "Bulk_S", 6, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6001", "Bulk_M", 431, 4),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6001", "Bulk_L", 119, 5),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6001", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6003", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6003", "Bulk_S", 6, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6003", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6003", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6003", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6006", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6006", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6006", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6006", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6006", "Bulk_XL", 122, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6007", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6007", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6007", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6007", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6007", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6011", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6011", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6011", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6011", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6011", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6013", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6013", "Bulk_S", 6, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6013", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6013", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6013", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6016", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6016", "Bulk_S", 6, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6016", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6016", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6016", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6020", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6020", "Bulk_S", 6, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6020", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6020", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6020", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6028", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6028", "Bulk_S", 6, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6028", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6028", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6028", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6029", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6029", "Bulk_S", 6, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6029", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6029", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6029", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6030", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6030", "Bulk_S", 6, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6030", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6030", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6030", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6031", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6031", "Bulk_S", 6, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6031", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6031", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6031", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6035", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6035", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6035", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6035", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6035", "Bulk_XL", 122, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6038", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6038", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6038", "Bulk_M", 431, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6038", "Bulk_L", 119, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6038", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6042", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6042", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6042", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6042", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6042", "Bulk_XL", 122, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6046", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6046", "Bulk_S", 6, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6046", "Bulk_M", 431, 4),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6046", "Bulk_L", 119, 5),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6046", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6052", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6052", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6052", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6052", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6052", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6054", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6054", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6054", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6054", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6054", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6056", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6056", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6056", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6056", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6056", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6058", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6058", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6058", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6058", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6058", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6059", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6059", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6059", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6059", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6059", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6061", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6061", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6061", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6061", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6061", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6066", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6066", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6066", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6066", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6066", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6082", "Bulk_XS", 5, 2),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6082", "Bulk_S", 6, 2),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6082", "Bulk_M", 431, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6082", "Bulk_L", 119, 4),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6082", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6089", "Bulk_XS", 5, 2),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6089", "Bulk_S", 6, 2),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6089", "Bulk_M", 431, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6089", "Bulk_L", 119, 4),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6089", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6101", "Bulk_XS", 5, 2),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6101", "Bulk_S", 6, 2),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6101", "Bulk_M", 431, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6101", "Bulk_L", 119, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6101", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6131", "Bulk_XS", 5, 2),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6131", "Bulk_S", 6, 2),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6131", "Bulk_M", 431, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6131", "Bulk_L", 119, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6131", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6199", "Bulk_XS", 5, 17),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6199", "Bulk_S", 6, 26),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6199", "Bulk_M", 431, 145),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6199", "Bulk_L", 119, 153),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6199", "Bulk_XL", 122, 125),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6221", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6221", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6221", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6221", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6221", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6222", "Bulk_XS", 5, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6222", "Bulk_S", 6, 0),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6222", "Bulk_M", 431, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6222", "Bulk_L", 119, 1),
    // createModalData( "DC1", "Dicte Overshirt Checked-Pale Blue/Black", "6222", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6001", "Bulk_XS", 3, 2),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6001", "Bulk_S", 63, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6001", "Bulk_M", 550, 8),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6001", "Bulk_L", 48, 5),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6001", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6003", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6003", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6003", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6003", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6003", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6006", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6006", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6006", "Bulk_M", 550, 2),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6006", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6006", "Bulk_XL", 122, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6007", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6007", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6007", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6007", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6007", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6011", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6011", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6011", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6011", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6011", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6013", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6013", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6013", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6013", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6013", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6016", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6016", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6016", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6016", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6016", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6020", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6020", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6020", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6020", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6020", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6028", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6028", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6028", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6028", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6028", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6029", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6029", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6029", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6029", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6029", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6030", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6030", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6030", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6030", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6030", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6031", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6031", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6031", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6031", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6031", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6035", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6035", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6035", "Bulk_M", 550, 2),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6035", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6035", "Bulk_XL", 122, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6038", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6038", "Bulk_S", 63, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6038", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6038", "Bulk_L", 48, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6038", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6042", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6042", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6042", "Bulk_M", 550, 2),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6042", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6042", "Bulk_XL", 122, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6046", "Bulk_XS", 3, 2),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6046", "Bulk_S", 63, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6046", "Bulk_M", 550, 8),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6046", "Bulk_L", 48, 5),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6046", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6052", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6052", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6052", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6052", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6052", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6054", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6054", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6054", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6054", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6054", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6056", "Bulk_XS", 3, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6056", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6056", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6056", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6056", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6058", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6058", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6058", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6058", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6058", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6059", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6059", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6059", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6059", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6059", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6061", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6061", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6061", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6061", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6061", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6066", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6066", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6066", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6066", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6066", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6082", "Bulk_XS", 3, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6082", "Bulk_S", 63, 5),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6082", "Bulk_M", 550, 7),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6082", "Bulk_L", 48, 4),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6082", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6089", "Bulk_XS", 3, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6089", "Bulk_S", 63, 4),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6089", "Bulk_M", 550, 7),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6089", "Bulk_L", 48, 4),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6089", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6101", "Bulk_XS", 3, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6101", "Bulk_S", 63, 4),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6101", "Bulk_M", 550, 7),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6101", "Bulk_L", 48, 4),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6101", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6131", "Bulk_XS", 3, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6131", "Bulk_S", 63, 4),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6131", "Bulk_M", 550, 7),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6131", "Bulk_L", 48, 4),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6131", "Bulk_XL", 122, 3),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6199", "Bulk_XS", 3, 66),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6199", "Bulk_S", 63, 111),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6199", "Bulk_M", 550, 278),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6199", "Bulk_L", 48, 161),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6199", "Bulk_XL", 122, 119),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6221", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6221", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6221", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6221", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6221", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6222", "Bulk_XS", 3, 0),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6222", "Bulk_S", 63, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6222", "Bulk_M", 550, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6222", "Bulk_L", 48, 1),
    // createModalData( "DC1", "Jada Crossover Rib Knit Top-Mint", "6222", "Bulk_XL", 122, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6001", "Bulk_XS", 10, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6001", "Bulk_S", 97, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6001", "Bulk_M", 248, 5),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6001", "Bulk_L", 52, 3),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6001", "Bulk_XL", 43, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6003", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6003", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6003", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6003", "Bulk_L", 52, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6003", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6006", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6006", "Bulk_S", 97, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6006", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6006", "Bulk_L", 52, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6006", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6007", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6007", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6007", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6007", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6007", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6011", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6011", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6011", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6011", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6011", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6013", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6013", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6013", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6013", "Bulk_L", 52, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6013", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6016", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6016", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6016", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6016", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6016", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6020", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6020", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6020", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6020", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6020", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6028", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6028", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6028", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6028", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6028", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6029", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6029", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6029", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6029", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6029", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6030", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6030", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6030", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6030", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6030", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6031", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6031", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6031", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6031", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6031", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6035", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6035", "Bulk_S", 97, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6035", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6035", "Bulk_L", 52, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6035", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6038", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6038", "Bulk_S", 97, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6038", "Bulk_M", 248, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6038", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6038", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6042", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6042", "Bulk_S", 97, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6042", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6042", "Bulk_L", 52, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6042", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6046", "Bulk_XS", 10, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6046", "Bulk_S", 97, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6046", "Bulk_M", 248, 5),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6046", "Bulk_L", 52, 3),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6046", "Bulk_XL", 43, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6052", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6052", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6052", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6052", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6052", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6054", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6054", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6054", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6054", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6054", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6056", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6056", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6056", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6056", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6056", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6058", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6058", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6058", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6058", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6058", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6059", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6059", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6059", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6059", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6059", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6061", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6061", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6061", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6061", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6061", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6066", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6066", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6066", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6066", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6066", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6082", "Bulk_XS", 10, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6082", "Bulk_S", 97, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6082", "Bulk_M", 248, 4),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6082", "Bulk_L", 52, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6082", "Bulk_XL", 43, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6089", "Bulk_XS", 10, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6089", "Bulk_S", 97, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6089", "Bulk_M", 248, 4),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6089", "Bulk_L", 52, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6089", "Bulk_XL", 43, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6101", "Bulk_XS", 10, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6101", "Bulk_S", 97, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6101", "Bulk_M", 248, 4),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6101", "Bulk_L", 52, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6101", "Bulk_XL", 43, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6131", "Bulk_XS", 10, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6131", "Bulk_S", 97, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6131", "Bulk_M", 248, 4),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6131", "Bulk_L", 52, 2),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6131", "Bulk_XL", 43, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6199", "Bulk_XS", 10, 37),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6199", "Bulk_S", 97, 63),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6199", "Bulk_M", 248, 157),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6199", "Bulk_L", 52, 91),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6199", "Bulk_XL", 43, 67),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6221", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6221", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6221", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6221", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6221", "Bulk_XL", 43, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6222", "Bulk_XS", 10, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6222", "Bulk_S", 97, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6222", "Bulk_M", 248, 1),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6222", "Bulk_L", 52, 0),
    // createModalData( "DC1", "Jolene Ribbed Wrap Midi Skirt-Mint", "6222", "Bulk_XL", 43, 0),
  ]

  function renderPlus(){
      return <a title="Add" href=" " style={{textDecoration: "none"}}><h3 style={{color: "#327ab7", fontWeight: "bold", cursor: "pointer", fontSize: "20px"}}> + </h3></a>
  }

  function renderMinus(){
    return <a title="Remove" href="" style={{textDecoration: "none"}}><h3 style={{color: "#327ab7", fontWeight: "bold", cursor: "pointer", fontSize: "20px"}}> - </h3></a>
}

// Styling 
// =========================================================
  const useStyles = makeStyles({
    root: {
      width: '100%',
    },
    container: {
      maxHeight: 440,
    },
  });

// Data Table function 
// =========================================================
  export default function StickyHeadTable() {
    const classes = useStyles();
    
    return (
      <Paper className={classes.root}>
        <TableContainer className={classes.container}>
          <Table stickyHeader aria-label="sticky table">
            <TableHead>
              <TableRow>
                {columnsModal.map(column => (
                  <TableCell
                    key={column.id}
                    align={column.align}
                    style={{ width: column.minWidth }}
                  >
                   <h3 style={{color: "#327ab7", fontWeight: "bold"}}>{column.label}</h3>
                    
                  </TableCell>
                ))}
              </TableRow>
            </TableHead>
            <TableBody>
              {rowsModal.map(row => {
                return (
                  <TableRow hover role="checkbox" tabIndex={-1} key={row.stycId}>
                    {columnsModal.map(column => {
                      const value = row[column.id];
                      return (
                        <TableCell key={column.id} align={column.align} className={column < 0 ? "" : "warning"}>
                          {column.format && typeof value === 'number' ? column.format(value) : value}
                        </TableCell>
                      );
                    })}
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        </TableContainer>
      </Paper>
    );
  }